"""create_initial_schema

Revision ID: 0fb1907eebf9
Revises: 
Create Date: 2026-06-15 09:55:46.048503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fb1907eebf9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('query_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('institution_slug', sa.String(length=50), nullable=False),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('response_text', sa.Text(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('cache_hit', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_query_logs_institution_slug'), 'query_logs', ['institution_slug'], unique=False)
    op.create_table('scrape_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('institution_slug', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('pages_scraped', sa.Integer(), nullable=False),
    sa.Column('points_upserted', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scrape_jobs_institution_slug'), 'scrape_jobs', ['institution_slug'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scrape_jobs_institution_slug'), table_name='scrape_jobs')
    op.drop_table('scrape_jobs')
    op.drop_index(op.f('ix_query_logs_institution_slug'), table_name='query_logs')
    op.drop_table('query_logs')
    # ### end Alembic commands ###
